---
title: "About the project"
css: mystyle.css
---

The main reasons to embark on this Project are: (1) the wrong idea students have in relation to Statistics, as they frequently associate it to a set of theoretical results without real application; (2) the necessity to implement educational cohesion measures between related subjects that would allow the student to follow the natural sequence of theoretical concepts and their application; (3) to enhance students’ motivation through the resolution of actual problems by the application of theoretical concepts they already know; (4) to acquaint the students with the eventual problems they may encounter in positions in companies or institutions in which a quantitative profile is required and, at the same time, to strengthen their CV for their future employability.
 
Specifically, weekly sessions (voluntary and additional to the statutory lessons) will be scheduled in which the professor will introduce current problems of remarkable notoriety in the business or institutional sectors, These problems will be solved in a ‘friendly’ way by the application of statistical concepts studied in related courses/subjects. For their resolution, the use of the most commonly used software will be necessary and, thus, an IT classroom is required.
 
For the selection of the cases to be solved, a research process has been carried out based on current job offers (LinkedIn, Infojobs, etc.) where the employers’ requirements are related to the resolution of an explicit quantitative case. Among all offers, the most frequent will be chosen, as long as they can be adapted to the students’ knowledge. For their resolution, the software and procedures will be chosen accordingly, keeping the balance between what is required and the appropriateness of the software used in order to solve them.
 
The sessions will be structured in four phases. Firstly, with the aim of giving the students the feeling that what they will be learning is real and of particular relevance, the problem will be exposed by showing them the job offers, videos, press notes, documents, etc., in which the interest of the problem is explained. Secondly, professor and students will think about the statistical concepts already learned that could be useful in the resolution of the problem. In this way, students will be part of a recreated business/institution environment and will therefore feel involved in the resolution of the problem. Thirdly, professor and students will work together in solving the problem making use of the adequate tools, thus exploring the link between theory and applicability. Finally, students will present their results, with the aim of recreating a situation as close to reality as possible. These results will be presented orally and as classic and dynamic (Shiny App) reports.
 
The aim of this project is to show the students how useful the concepts they are learning actually are, and to develop the capability to use their critic judgment when thinking about the application of such concepts. Additionally, students will hopefully increase their motivation of acquiring a knowledge that will help them in their way into the labor market, both strengthening their quantitative profiles and by having a first glimpse of what they may encounter[^*]. Furthermore, these sessions will serve as a connecting link among similar subjects, so that students will be able to see the connection and coordination between them and thus find it easier to understand their relationships.

[^*]:
Big Data Specialists are one of the most demanded professions, according to the «XI Informe Los + Buscados en 2016» report, created by Adecco. «The appearing professions are related to data anlytics, statistics and mathematics. Experts in dealing with the amounts of information accumulated in the Big Data cloud are required. Almost all companies have large amounts of data about their clients and users. It is necessary to make use of this information in order to provide a better service » explains the director of Public Policies and Institutional Relationships in Google Spain and Portugal.