---
title: "Recommender Systems"
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: true
    css: mystyle.css
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE
)
```

## Brief Explanation 

Almost every people has receipt a recommendation from them even if he/she has never heard about it.  Selling websites like Amazon or simple browsers as Google’s are training models from data in order to provide the best product or website to their customers given some information such as sociodemographic characteristics, historical purchased products or likes in websites. Obviously, recommender systems are on the spot of many companies and institutions who are trying to provide the most adequate item for a given person.  The concept and its typologies are motivated by illustrative examples obtained from recommender systems that are currently working. The final goal is to build a recommender systems from the scratch for a real problem.

This page contains a combination of traditional lecture materials (slides) and code demonstrating the relevant methods. The course will proceed by working through both. We will use several recent packages in our examples; see the [About](./About.html) page for information about the package versions.

## Practical example
